name: Check Pull Request

on: [pull_request]

permissions:
  contents: read

runs:
  using: "composite"
  steps:

jobs:
  Check-Url-Shortener-Service:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform Init
        working-directory: src/infrastructure/aws/envs/dev
        run: terraform init -no-color -backend=false

      - name: Terraform Validate
        working-directory: src/infrastructure/aws/envs/dev
        run: terraform validate

      - name: Docker Compose Up
        working-directory: src
        run: docker compose -f docker-compose.yaml -f docker-compose.backend.yaml --progress=plain up -d --force-recreate --build

      - name: Check Swagger
        run: curl --fail --retry 5 --retry-max-time 120 --retry-delay 5 -v http://172.17.0.1:8080/swagger/index.html
