name: Terraform aws dev deployment

on:
  push:
    branches:
      - master
      - stories/initial-setup
  workflow_dispatch:
    branches:
      - master

permissions:
  contents: read
  #issues: write

jobs:
  uss-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform Init
        run: terraform init -no-color

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan.json

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan.json


