name: Deployment Url-Shortener-Service on dev@aws

on:
  push:
    branches:
      - master
      - stories/initial-setup
  workflow_dispatch:
    branches:
      - master

permissions:
  contents: read

jobs:
  Deploy-Url-Shortener-Service:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"

      - name: Terraform Init
        working-directory: src/infrastructure/aws/envs/dev
        run: terraform init -no-color

      - name: Terraform Validate
        working-directory: src/infrastructure/aws/envs/dev
        run: terraform validate

      - name: Terraform Apply ECR
        working-directory: src/infrastructure/aws/envs/dev
        run: terraform apply -auto-approve -input=false -no-color -target module.url-shortener-service.module.ecr "-var=docker_image_tag=v${{ github.run_number }}"

      - name: Terraform Apply
        working-directory: src/infrastructure/aws/envs/dev
        run: terraform apply -auto-approve -input=false -no-color "-var=docker_image_tag=v${{ github.run_number }}"


